name: beauty_parlor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  carousel_slider: ^4.1.1
  easy_dynamic_theme: ^2.2.0
  firebase_core: ^1.15.0
  font_awesome_flutter: any
  form_builder_validators: any

  # Google Sign In
  firebase_auth: ^3.3.16
  google_sign_in: ^5.3.0
  google_sign_in_web: ^0.10.1

  intl: ^0.17.0
  url_launcher: ^6.1.0
  firebase_database: ^9.0.12
  flutter_signin_button: ^2.0.0
  flutter_form_builder: any

  # State Management
  provider: ^6.0.2

  flutter_svg: 1.0.3
  google_fonts: ^2.3.2
  data_table_2: ^2.2.1
  adaptive_theme: ^2.3.1

  # Online firebase Storage for Files
  firebase_storage: ^10.2.14

  #online Database for Data
  cloud_firestore: ^3.1.13

  pie_chart: ^5.3.0
  connectivity_plus: ^2.3.0
  flutter_mailer: ^2.0.1
  get_it: ^7.2.0
  firebase_analytics: ^9.1.6
  image_picker_web: any
  mime: ^1.0.1
  mime_type: ^1.0.0
  image_picker: any
  path: any
  firebase_dart: any
  syncfusion_flutter_datagrid: ^20.1.51
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3
  equatable: ^2.0.3
  flutterfire_ui: ^0.4.0+4
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
